import type { Product } from "@/components/shop/product-card";

export const FEATURED_PRODUCTS: Product[] = [
  {
    slug: "stol-river",
    title: "Журнальный стол River",
    price: "от 48 000 ₽",
    image: "/product-stol-river.webp",
    badge: "hit",
  },
  {
    slug: "fotaramka-30x40-a4",
    title: "Фоторамка 30×40 под фото А4",
    price: "от 22 000 ₽",
    image: "/product-fotaramka-30x40.webp",
    badge: "new",
  },
  {
    slug: "podnos-zoloto",
    title: "Сервировочный поднос",
    price: "8 900 ₽",
    image: "/product-podnos.webp",
    badge: "sale",
  },
  {
    slug: "chasy-live",
    title: "Часы Live Edge",
    price: "от 12 500 ₽",
    image: "/product-chasy-live.webp",
  },
];

export const ALL_PRODUCTS: Product[] = [
  ...FEATURED_PRODUCTS,
  {
    slug: "eloch-igrushki-2d",
    title: "Ёлочные 2D игрушки",
    price: "от 1 200 ₽",
    image: "/product-eloch-igrushki.webp",
    badge: "new",
  },
  {
    slug: "podstavka",
    title: "Подставка под украшения",
    price: "4 800 ₽",
    image: "/product-podstavka.webp",
  },
  {
    slug: "stolik-zavtrak-utro",
    title: "Столик для завтрака «Утро» — компактный",
    price: "от 9 800 ₽",
    image: "/product-stol-river.webp",
    badge: "new",
  },
  {
    slug: "stolik-zavtrak-live-sage",
    title: "Столик для завтрака Live Edge, шалфей и смола",
    price: "от 14 200 ₽",
    image: "/product-stol-river.webp",
  },
  {
    slug: "stolik-zavtrak-skladnoj",
    title: "Складной столик для завтрака в постель",
    price: "от 11 500 ₽",
    image: "/product-podnos.webp",
    badge: "hit",
  },
  {
    slug: "stolik-zavtrak-bortiki",
    title: "Столик с бортиками и ручками для переноски",
    price: "от 12 900 ₽",
    image: "/product-stol-river.webp",
  },
  {
    slug: "stolik-zavtrak-noutbuk",
    title: "Столик для ноутбука и завтрака в постели",
    price: "от 13 400 ₽",
    image: "/product-podstavka.webp",
  },
  {
    slug: "stolik-zavtrak-podarok",
    title: "Подарочный столик для завтрака премиум",
    price: "от 16 800 ₽",
    image: "/product-fotaramka-30x40.webp",
    badge: "new",
  },
  {
    slug: "tarelka-dekor-shalfej",
    title: "Декоративная тарелка «Шалфей» — смола и дерево",
    price: "от 4 200 ₽",
    image: "/product-podnos.webp",
    badge: "new",
  },
  {
    slug: "blyudo-servirovochnoe-epoks",
    title: "Сервировочное блюдо из эпоксидной смолы",
    price: "от 5 800 ₽",
    image: "/product-stol-river.webp",
  },
  {
    slug: "tarelka-zakuski-syrnaya",
    title: "Тарелка для закусок и сырной нарезки",
    price: "от 3 900 ₽",
    image: "/product-podstavka.webp",
  },
  {
    slug: "nabor-tarelok-desert",
    title: "Набор из 2 десертных тарелок ручной работы",
    price: "от 8 600 ₽",
    image: "/product-fotaramka-30x40.webp",
    badge: "hit",
  },
  {
    slug: "blyudo-centralnoe-stol",
    title: "Центральное блюдо для стола (панно-сервировка)",
    price: "от 9 200 ₽",
    image: "/product-podnos.webp",
  },
  {
    slug: "tarelka-podarochnaya",
    title: "Подарочная тарелка премиум из смолы и слэба",
    price: "от 7 400 ₽",
    image: "/product-stol-river.webp",
    badge: "new",
  },
  {
    slug: "podnos-suhocvety-laguna",
    title: "Поднос с сухоцветами «Лагуна» в эпоксидной смоле",
    price: "от 10 200 ₽",
    image: "/product-fotaramka-30x40.webp",
    badge: "new",
  },
  {
    slug: "podnos-live-edge-moss",
    title: "Поднос Live Edge — мох, дерево и прозрачная смола",
    price: "от 9 600 ₽",
    image: "/product-stol-river.webp",
  },
  {
    slug: "podnos-zavtrak-kofe",
    title: "Мини-поднос для завтрака и кофе",
    price: "от 6 400 ₽",
    image: "/product-podnos.webp",
    badge: "hit",
  },
  {
    slug: "podnos-dekor-interer",
    title: "Декоративный поднос для интерьера и свечей",
    price: "от 7 800 ₽",
    image: "/product-podstavka.webp",
  },
  {
    slug: "podnos-podarochnyj-set",
    title: "Подарочный поднос премиум в фирменной упаковке",
    price: "от 12 400 ₽",
    image: "/product-podnos.webp",
    badge: "new",
  },
  {
    slug: "chasy-suhocvety-laguna",
    title: "Настенные часы с сухоцветами «Лагуна»",
    price: "от 13 800 ₽",
    image: "/product-chasy-live.webp",
    badge: "new",
  },
  {
    slug: "chasy-kvadrat-noir",
    title: "Квадратные часы минимализм, смола и латунь",
    price: "от 11 200 ₽",
    image: "/product-chasy-live.webp",
  },
  {
    slug: "chasy-sleb-graphit",
    title: "Часы из слэба и графитовой эпоксидной смолы",
    price: "от 14 500 ₽",
    image: "/product-stol-river.webp",
    badge: "hit",
  },
  {
    slug: "chasy-foto-smola",
    title: "Часы с фотографией в заливке эпоксидной смолы",
    price: "от 15 900 ₽",
    image: "/product-fotaramka-30x40.webp",
    badge: "new",
  },
  {
    slug: "chasy-moh-zelenyj",
    title: "Круглые часы с мхом и зелёной смолой",
    price: "от 12 900 ₽",
    image: "/product-chasy-live.webp",
  },
  {
    slug: "panno-more-golubaya",
    title: "Панно «Морская глубина» из эпоксидной смолы",
    price: "от 18 500 ₽",
    image: "/product-stol-river.webp",
    badge: "hit",
  },
  {
    slug: "kartina-abstrakciya-sage",
    title: "Абстрактная картина «Шалфей и туман»",
    price: "от 14 200 ₽",
    image: "/product-fotaramka-30x40.webp",
    badge: "new",
  },
  {
    slug: "panno-kamni-glass",
    title: "Панно с камнями в прозрачной эпоксидной смоле",
    price: "от 16 800 ₽",
    image: "/product-podnos.webp",
  },
  {
    slug: "kartina-minimal-pesok",
    title: "Минималистичное панно «Песок и линия»",
    price: "от 11 900 ₽",
    image: "/product-podstavka.webp",
  },
  {
    slug: "panno-diptih-more",
    title: "Диптих «Морской горизонт» — два полотна",
    price: "от 28 000 ₽",
    image: "/product-chasy-live.webp",
    badge: "new",
  },
  {
    slug: "doska-servirovochnaja-syr",
    title: "Сервировочная доска для сыра — орех и эпоксидная смола",
    price: "от 8 900 ₽",
    image: "/product-podnos.webp",
    badge: "hit",
  },
  {
    slug: "menazhnica-3-sekcii",
    title: "Менажница на 3 секции из дерева и смолы",
    price: "от 11 200 ₽",
    image: "/product-stol-river.webp",
    badge: "new",
  },
  {
    slug: "doska-live-edge-oval",
    title: "Овальная сервировочная доска Live Edge",
    price: "от 9 600 ₽",
    image: "/product-podnos.webp",
  },
  {
    slug: "doska-frukty-river",
    title: "Доска для фруктов с прозрачной «речной» смолой",
    price: "от 7 800 ₽",
    image: "/product-fotaramka-30x40.webp",
  },
  {
    slug: "menazhnica-zakuski",
    title: "Менажница для закусок и антипасти",
    price: "от 12 400 ₽",
    image: "/product-podstavka.webp",
    badge: "new",
  },
  {
    slug: "doska-premium-podarok",
    title: "Подарочная сервировочная доска премиум",
    price: "от 14 800 ₽",
    image: "/product-stol-river.webp",
  },
];
