import type { Product } from "@/components/shop/product-card";

export function catalogProductGalleryImages(product: Product): string[] {
  return product.images && product.images.length > 0
    ? product.images
    : [product.image];
}

export const FEATURED_PRODUCTS: Product[] = [
  {
    slug: "stol-river",
    title: "Журнальный стол River",
    price: "от 48 000 ₽",
    priceFromRub: 48_000,
    category: "stoly",
    image: "/product-stol-river.webp",
    badge: "hit",
  },
  {
    slug: "fotaramka-30x40-a4",
    title: "Фоторамка из эпоксидной смолы и сухоцветов",
    price: "от 9 000 ₽",
    priceFromRub: 9_000,
    category: "bukety",
    image: "/product-fotaramka-suhocvety.webp",
    images: [
      "/product-fotaramka-suhocvety.webp",
      "/product-fotaramka-suhocvety-2.webp",
      "/product-fotaramka-suhocvety-3.webp",
      "/product-fotaramka-suhocvety-4.webp",
    ],
    badge: "new",
  },
  {
    slug: "podnos-zoloto",
    title: "Сервировочный поднос",
    price: "8 900 ₽",
    priceFromRub: 8_900,
    category: "posuda",
    image: "/product-podnos.webp",
    badge: "sale",
  },
  {
    slug: "chasy-live",
    title: "Часы Live Edge",
    price: "от 12 500 ₽",
    priceFromRub: 12_500,
    category: "chasy",
    image: "/product-chasy-live.webp",
  },
];

export const ALL_PRODUCTS: Product[] = [
  ...FEATURED_PRODUCTS,
  {
    slug: "eloch-igrushki-2d",
    title: "Ёлочные 2D игрушки",
    price: "от 1 200 ₽",
    priceFromRub: 1_200,
    category: "dekor",
    image: "/product-eloch-igrushki.webp",
    badge: "new",
  },
  {
    slug: "podstavka",
    title: "Подставка под украшения",
    price: "4 800 ₽",
    priceFromRub: 4_800,
    category: "dekor",
    image: "/product-podstavka.webp",
  },
  {
    slug: "stolik-zavtrak-utro",
    title: "Столик для завтрака «Утро» — компактный",
    price: "от 9 800 ₽",
    priceFromRub: 9_800,
    category: "stoly",
    image: "/product-stolik-zavtrak-utro.webp",
    badge: "new",
  },
  {
    slug: "stolik-zavtrak-live-sage",
    title: "Столик для завтрака Live Edge, шалфей и смола",
    price: "от 14 200 ₽",
    priceFromRub: 14_200,
    category: "stoly",
    image: "/product-stolik-zavtrak-live-sage.webp",
  },
  {
    slug: "stolik-zavtrak-skladnoj",
    title: "Складной столик для завтрака в постель",
    price: "от 11 500 ₽",
    priceFromRub: 11_500,
    category: "stoly",
    image: "/product-stolik-zavtrak-skladnoj.webp",
    badge: "hit",
  },
  {
    slug: "tarelka-dekor-shalfej",
    title: "Декоративная тарелка «Перо» — смола и поталь",
    price: "от 4 200 ₽",
    priceFromRub: 4_200,
    category: "posuda",
    image: "/product-tarelka-dekor-pero.webp",
    badge: "new",
  },
  {
    slug: "blyudo-servirovochnoe-epoks",
    title: "Сервировочное блюдо из эпоксидной смолы",
    price: "от 5 800 ₽",
    priceFromRub: 5_800,
    category: "posuda",
    image: "/product-blyudo-servirovochnoe-epoks.webp",
  },
  {
    slug: "tarelka-zakuski-syrnaya",
    title: "Тарелка для закусок и сырной нарезки",
    price: "от 9 500 ₽",
    priceFromRub: 9_500,
    category: "posuda",
    image: "/product-tarelka-zakuski-syrnaya.webp",
  },
  {
    slug: "nabor-tarelok-desert",
    title: "Набор из 2 десертных тарелок ручной работы",
    price: "от 3 500 ₽",
    priceFromRub: 3_500,
    category: "posuda",
    image: "/product-nabor-tarelok-desert.webp",
    badge: "hit",
  },
  {
    slug: "blyudo-centralnoe-stol",
    title: "Центральное блюдо для стола (панно-сервировка)",
    price: "от 9 200 ₽",
    priceFromRub: 9_200,
    category: "posuda",
    image: "/product-blyudo-centralnoe-stol.webp",
  },
  {
    slug: "tarelka-podarochnaya",
    title: "Подарочный поднос премиум из смолы и кофейных зерен",
    price: "от 7 400 ₽",
    priceFromRub: 7_400,
    category: "posuda",
    image: "/product-tarelka-podarochnaya.webp",
    badge: "new",
  },
  {
    slug: "podnos-suhocvety-laguna",
    title: "Поднос с сухоцветами «Весна» в эпоксидной смоле",
    price: "от 10 200 ₽",
    priceFromRub: 10_200,
    category: "posuda",
    image: "/product-podnos-suhocvety-vesna.webp",
    badge: "new",
  },
  {
    slug: "podnos-live-edge-moss",
    title: "Подставки с каменной фактурой",
    price: "от 1 500 ₽",
    priceFromRub: 1_500,
    category: "dekor",
    image: "/product-podstavki-kamennaya-faktura.webp",
  },
  {
    slug: "podnos-zavtrak-kofe",
    title: "Подставка пасхальная для яиц",
    price: "от 4 500 ₽",
    priceFromRub: 4_500,
    category: "dekor",
    image: "/product-podstavka-paskhalnaya-yajca.webp",
    badge: "hit",
  },
  {
    slug: "podnos-dekor-interer",
    title: "Декоративный поднос для интерьера и свечей",
    price: "от 7 800 ₽",
    priceFromRub: 7_800,
    category: "posuda",
    image: "/product-podnos-dekor-interer.webp",
  },
  {
    slug: "podnos-podarochnyj-set",
    title: "Подарочный поднос премиум в фирменной упаковке",
    price: "от 12 400 ₽",
    priceFromRub: 12_400,
    category: "posuda",
    image: "/product-podnos.webp",
    badge: "new",
  },
  {
    slug: "chasy-suhocvety-laguna",
    title: "Настенные часы с платами «Программист»",
    price: "от 13 800 ₽",
    priceFromRub: 13_800,
    category: "chasy",
    image: "/product-chasy-programmist.webp",
    badge: "new",
  },
  {
    slug: "chasy-kvadrat-noir",
    title: "Квадратные часы минимализм, смола и серебро",
    price: "от 11 200 ₽",
    priceFromRub: 11_200,
    category: "chasy",
    image: "/product-chasy-kvadrat-serebro.webp",
  },
  {
    slug: "chasy-sleb-graphit",
    title: "Часы жеода с натуральными камнями",
    price: "от 14 500 ₽",
    priceFromRub: 14_500,
    category: "chasy",
    image: "/product-chasy-zheoda-kamni.webp",
    badge: "hit",
  },
  {
    slug: "chasy-foto-smola",
    title: "Часы жеода «Чёрное золото»",
    price: "от 15 900 ₽",
    priceFromRub: 15_900,
    category: "chasy",
    image: "/product-chasy-zheoda-chernoe-zoloto.webp",
    badge: "new",
  },
  {
    slug: "chasy-moh-zelenyj",
    title: "Круглые часы с натуральными камнями и голубой смолой",
    price: "от 12 900 ₽",
    priceFromRub: 12_900,
    category: "chasy",
    image: "/product-chasy-golubaya-kamni.webp",
  },
  {
    slug: "panno-more-golubaya",
    title: "Панно «Морская глубина» из эпоксидной смолы",
    price: "от 18 500 ₽",
    priceFromRub: 18_500,
    category: "kartiny",
    image: "/product-panno-morskaya-glubina.webp",
    badge: "hit",
  },
  {
    slug: "kartina-abstrakciya-sage",
    title: "Абстрактная картина «Шалфей и туман»",
    price: "от 14 200 ₽",
    priceFromRub: 14_200,
    category: "kartiny",
    image: "/product-kartina-shalfej-tuman.webp",
    badge: "new",
  },
  {
    slug: "panno-kamni-glass",
    title: "Панно с камнями и подсветкой",
    price: "от 16 800 ₽",
    priceFromRub: 16_800,
    category: "kartiny",
    image: "/product-panno-kamni-podsvetka.webp",
  },
  {
    slug: "kartina-minimal-pesok",
    title: "Минималистичное панно «Песок и линия»",
    price: "от 11 900 ₽",
    priceFromRub: 11_900,
    category: "kartiny",
    image: "/product-panno-pesok-liniya.webp",
  },
  {
    slug: "panno-diptih-more",
    title: "Вывеска для бизнеса с эпоксидной смолой и натуральными камнями",
    price: "от 28 000 ₽",
    priceFromRub: 28_000,
    category: "kartiny",
    image: "/product-vyveska-biznes-kamni.webp",
    badge: "new",
  },
  {
    slug: "doska-servirovochnaja-syr",
    title: "Сервировочная доска для сыра — орех и эпоксидная смола",
    price: "от 8 900 ₽",
    priceFromRub: 8_900,
    category: "posuda",
    image: "/product-doska-syr-more.webp",
    badge: "hit",
  },
  {
    slug: "menazhnica-3-sekcii",
    title: "Рама для зеркала с фактурой под камень 50 см",
    price: "25 000 ₽",
    priceFromRub: 25_000,
    category: "dekor",
    image: "/product-rama-zerkalo-kamen.webp",
    badge: "new",
  },
  {
    slug: "doska-live-edge-oval",
    title: "Столешница из эпоксидной смолы для кухни",
    price: "от 9 600 ₽",
    priceFromRub: 9_600,
    category: "stoly",
    image: "/product-stoleshnica-kuhnya.webp",
  },
  {
    slug: "doska-frukty-river",
    title: "Поднос для кофе и десерта",
    price: "2 500 ₽",
    priceFromRub: 2_500,
    category: "posuda",
    image: "/product-podnos-kofe-desert.webp",
  },
  {
    slug: "menazhnica-zakuski",
    title: "Шкатулка для украшений",
    price: "от 9 000 ₽",
    priceFromRub: 9_000,
    category: "dekor",
    image: "/product-shkatulka-ukrashenij.webp",
    badge: "new",
  },
  {
    slug: "doska-premium-podarok",
    title: "Нарды 60 см из смолы и дерева",
    price: "от 45 000 ₽",
    priceFromRub: 45_000,
    category: "dekor",
    image: "/product-nardy-60-sm.webp",
    badge: "hit",
  },
  {
    slug: "vaza-smola-derevo-suhocvety",
    title: "Ваза из смолы, дерева и сухоцветов",
    price: "от 25 000 ₽",
    priceFromRub: 25_000,
    category: "dekor",
    image: "/product-vaza-suhocvety-smola.webp",
    badge: "new",
  },
  {
    slug: "kub-smola-suhocvety",
    title: "Куб из смолы и сухоцветов",
    price: "от 15 000 ₽",
    priceFromRub: 15_000,
    category: "bukety",
    image: "/product-kub-suhocvety-smola-4.webp",
    images: [
      "/product-kub-suhocvety-smola-4.webp",
      "/product-kub-suhocvety-smola.webp",
      "/product-kub-suhocvety-smola-2.webp",
      "/product-kub-suhocvety-smola-3.webp",
      "/product-kub-suhocvety-smola-5.webp",
      "/product-kub-suhocvety-smola-6.webp",
      "/product-kub-suhocvety-smola-7.webp",
      "/product-kub-suhocvety-smola-8.webp",
      "/product-kub-suhocvety-smola-9.webp",
      "/product-kub-suhocvety-smola-10.webp",
      "/product-kub-suhocvety-smola-11.webp",
    ],
    badge: "new",
  },
  {
    slug: "panno-stena-suhocvety",
    title: "Панно на стену из смолы с цветами",
    price: "от 19 000 ₽",
    priceFromRub: 19_000,
    category: "bukety",
    image: "/product-panno-stena-cvety.webp",
    images: [
      "/product-panno-stena-cvety.webp",
      "/product-panno-stena-cvety-2.webp",
      "/product-panno-stena-cvety-3.webp",
      "/product-panno-stena-cvety-4.webp",
      "/product-panno-stena-cvety-5.webp",
      "/product-panno-stena-cvety-6.webp",
    ],
    badge: "new",
  },
  {
    slug: "stol-spil-otverstie",
    title: "Стол из спила с природным отверстием",
    price: "от 23 000 ₽",
    priceFromRub: 23_000,
    category: "stoly",
    image: "/product-stol-spil-otverstie.webp",
    badge: "new",
  },
];
